#ifndef MAT_ALG_H
#define MAT_ALG_H

#include <stdio.h>
#include <stdlib.h>

typedef struct matrix mat;

//DO NOT EDIT THIS FILE

mat* matrix_multiply(mat* A, mat* B);

mat* matrix_add(mat* A, mat* B);

mat* matrix_read(char* filename);

mat* create_matrix(int n, int m);

int matrix_write(char* filename, mat* A);

void matrix_free(mat*A);

mat* matrix_scale(double c, mat* A);

#endif
